### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by cjessett** [BeejLuig/1-tdd-vidbits#4]
(Meets Expectations) Overall, nice work.

Remember to be consistent with whitespace throughout your code. Also, remember that you only need `async` functions when there is an `await` call and you should handle the case when resources are not found in your routes.

Otherwise, your code is clean and easy to follow, nice job.

**Comment by BeejLuig** [comment]
Fixed issues 1-3. Thanks for the review @cjessett !
